---
###
# Copyright 2018 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###

- name: osh_schemas - create output directories
  file:
    path: "{{ __iimam_osh.dest }}"
    state: directory
  with_items: "{{ osh_schemas }}"
  loop_control:
    loop_var: __iimam_osh
    label: "{{ __iimam_osh.dest }}"

- name: osh_schemas - copy DDL for generation
  copy:
    src: "{{ __iimam_osh.ddl }}"
    dest: "{{ __iimam_osh.dest }}/{{ __iimam_osh.ddl | basename }}"
  with_items: "{{ osh_schemas }}"
  loop_control:
    loop_var: __iimam_osh
    label: "{{ __iimam_osh.ddl }}"

- name: osh_schemas - generate OSH schema for each table
  imam_generate_osh:
    ddl: "{{ __iimam_osh.dest }}/{{ __iimam_osh.ddl | basename }}"
    structure: "{{ __iimam_osh.structure }}"
    recordfmt: "{{ __iimam_osh.recordfmt }}"
    ext: "{{ __iimam_osh.fileext }}"
    tables: "{{ __iimam_osh.tables | default(omit) }}"
    dest: "{{ __iimam_osh.dest }}"
  with_items: "{{ osh_schemas }}"
  register: __ibm_infosvr_metadata_asset_mgr_osh_schemas
  loop_control:
    loop_var: __iimam_osh
    label: "{{ __iimam_osh.ddl }}"

- name: osh_schemas - check for any unmapped DDL
  assert:
    that:
      - __iimam_oshr.unmapped | length == 0
    msg: "Unimplemented mappings in DDL: {{ __iimam_oshr.unmapped }}"
  with_items: "{{ __ibm_infosvr_metadata_asset_mgr_osh_schemas.results }}"
  loop_control:
    loop_var: __iimam_oshr
    label: "{{ __iimam_oshr.__iimam_osh.ddl }}"

- name: osh_schemas - create blank data files
  file:
    path: "{{ __iimam_oshr.1 | replace('.osh', '') }}"
    state: touch
  with_subelements:
    - "{{ __ibm_infosvr_metadata_asset_mgr_osh_schemas.results }}"
    - schemas
  loop_control:
    loop_var: __iimam_oshr
    label: "{{ __iimam_oshr.0.__iimam_osh.ddl }} - {{ __iimam_oshr.1 | replace('.osh', '') }}"

- name: osh_schemas - remove DDL used for generation
  file:
    path: "{{ __iimam_osh.dest }}/{{ __iimam_osh.ddl | basename }}"
    state: absent
  with_items: "{{ osh_schemas }}"
  loop_control:
    loop-var: __iimam_osh
    label: "{{ __iimam_osh.ddl }}"
